### PR TITLE
Enhancement: Adding new method Inc under drivers to allow rate limiting based on given variable count

### PR DESCRIPTION
**Pull request by Harry-027**
**### Description**

This is regarding the [issue](https://github.com/ulule/limiter/issues/170) raised before to support advanced use cases.
Raising PR to expose new method in order to increment Lua script counter by the number provided by user. This will facilitate and extend the library  functionality to support rate limiting graphql apis based on query complexity.

### CODE REVIEW

**Review by novln — COMMENTED** [review]
_A really nitpicking comment, sorry in advance._
Could you change `Inc` to `Increment` in the interface declaration?

Otherwise look good for me :+1: 

Thank you for your contribution :slightly_smiling_face:

**Comment by Harry-027** [comment]
> _A really nitpicking comment, sorry in advance._ Could you change `Inc` to `Increment` in the interface declaration?
> 
> Otherwise look good for me 👍
> 
> Thank you for your contribution 🙂

Thanks @novln ! I have made the required change. Could you release this as part of v3, since it's just an enhancement ? Would be really helpful if this is made available as soon as possible. Will be able to use this directly instead of maintaining my own fork :)

**Comment by novln** [comment]
Hello,

There is a new release: https://github.com/ulule/limiter/releases/tag/v3.9.0

Thank you again for your contribution :slightly_smiling_face:

**Comment by Harry-027** [comment]
> Hello,
> 
> There is a new release: https://github.com/ulule/limiter/releases/tag/v3.9.0
> 
> Thank you again for your contribution 🙂

Thanks @novln for releasing this 🚀 Much appreciated 🙂

**Pull request merged**
